"""Offer-level merchant policy rejection codes."""

from enum import StrEnum


class PolicyRejectionCode(StrEnum):
    MARGIN_BELOW_FLOOR = "MARGIN_BELOW_FLOOR"
    DISCOUNT_EXCEEDS_LIMIT = "DISCOUNT_EXCEEDS_LIMIT"
    DELIVERY_SUBSIDY_EXCEEDS_LIMIT = "DELIVERY_SUBSIDY_EXCEEDS_LIMIT"
    WARRANTY_SUBSIDY_EXCEEDS_LIMIT = "WARRANTY_SUBSIDY_EXCEEDS_LIMIT"
    BUNDLE_SUBSIDY_EXCEEDS_LIMIT = "BUNDLE_SUBSIDY_EXCEEDS_LIMIT"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    DELIVERY_DISABLED = "DELIVERY_DISABLED"
    WARRANTY_DISABLED = "WARRANTY_DISABLED"
    BUNDLE_DISABLED = "BUNDLE_DISABLED"
    RETURNS_DISABLED = "RETURNS_DISABLED"
    PRODUCT_INACTIVE = "PRODUCT_INACTIVE"
    MISSING_OPERATIONAL_DATA = "MISSING_OPERATIONAL_DATA"
    INTENT_DELIVERY_INCOMPATIBLE = "INTENT_DELIVERY_INCOMPATIBLE"
