"""Typed learning labels. FUTURE_REAL_COMMERCE is never populated here."""

from enum import StrEnum


class OutcomeSource(StrEnum):
    SIMULATED_ARENA = "SIMULATED_ARENA"
    SIMULATED_NEGOTIATION = "SIMULATED_NEGOTIATION"
    SIMULATED_TRANSACTION = "SIMULATED_TRANSACTION"
    FUTURE_REAL_COMMERCE = "FUTURE_REAL_COMMERCE"


class OutcomeType(StrEnum):
    SELECTED = "SELECTED"
    NOT_SELECTED = "NOT_SELECTED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COUNTERED = "COUNTERED"
    NO_PURCHASE = "NO_PURCHASE"
    TRANSACTION_CONFIRMED = "TRANSACTION_CONFIRMED"
    TRANSACTION_FAILED = "TRANSACTION_FAILED"


class ModelAlgorithm(StrEnum):
    LOGISTIC_REGRESSION = "LOGISTIC_REGRESSION"
    GRADIENT_BOOSTING = "GRADIENT_BOOSTING"
    PRICE_HEURISTIC = "PRICE_HEURISTIC"
    COLD_START_UTILITY = "COLD_START_UTILITY"


class ModelStatus(StrEnum):
    TRAINING = "TRAINING"
    CANDIDATE = "CANDIDATE"
    ACTIVE_EXPERIMENTAL = "ACTIVE_EXPERIMENTAL"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class ResponseModelMode(StrEnum):
    COLD_START = "COLD_START"
    LEARNED_EXPERIMENTAL = "LEARNED_EXPERIMENTAL"
